import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { Toaster } from "@/components/ui/sonner";
import AuthNav from "@/components/AuthNav";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children


}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="sticky top-0 z-40 w-full border-b border-border/60 backdrop-blur bg-background/60">
          <div className="container mx-auto px-6 h-14 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-md glass neon-glow-aqua" />
              <Link href="/" aria-label="Go to homepage" className="flex items-center h-10 md:h-11">
                <img src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/document-uploads/image-removebg-preview%20(16)-1758419437728.png" alt="Sustain-A-Prompt logo" className="object-contain !w-full !h-[60px] !max-w-full" />
              </Link>
            </div>
            <AuthNav />
          </div>
        </header>
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}' />

        {children}
        <VisualEditsMessenger />
        <Toaster />
      </body>
    </html>);

}